name: CI for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CI: false
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the version you need, e.g., 14, 16, or 18

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test -- --coverage --watch=false

    # Build the project
    - name: Build project
      run: npm run build

    # Optionally, deploy the app (for example, to GitHub Pages or Firebase Hosting)
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     deploy_branch: gh-pages
    #     folder: build

